### ISSUE TITLE
Can't install library using Anaconda.

### ISSUE THREAD

**Issue by IPuiggros** [coursekevin/weakformghnn#1]
Hi. I am currently unable to install the weakformghnn library through anaconda prompt. When running pip install git+https://github.com/coursekevin/weakformghnn#egg=weakformghnn i get the error:

Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\XXX\AppData\Local\Temp\pip-install-9nslk2i5\weakformghnn_2dd4a9862dad48e1ab2067e6704cd9ec\setup.py", line 4, in <module>
          long_description = fh.read()
        File "C:\Users\XXX\anaconda3\envs\GithubEnv\lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 2923: character maps to <undefined>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

How can this be solved? Is there any other way to install the library in a compatible way with anaconda?

Thank you in advance.

**Comment by coursekevin** [comment]
You can alternatively try installing the library in development mode. To do so first clone the repo and navigate into the `weakformghnn` directory. Then, with your conda environment activated, run:

```bash
pip install -e .
```

If this doesn't work, it might be a compatibility problem with your version of python. The code should work with python 3.7+.

**Comment by IPuiggros** [comment]
Thank you for the quick response. After cloning the repo using git bash, changing the directory to the weakformghnn folder in anaconda prompt, and running pip install -e git+https://github.com/coursekevin/weakformghnn#egg=weakformghnn, I get the same error again. My python version is 3.10.9 so it shouldn't be a compatibility issue. Did I misunderstood what you said?

Thanks in advance.

**Comment by coursekevin** [comment]
I actually mean try running: `pip install -e .` (with the period rather than the git+...) from the weakformghnn directory exactly. The period tells pip to install the package in the current directory.

I'm struggling to reproduce the error on my system. I can install the package from a fresh conda environment with python 3.10.9. 

If the above doesn't work you can try replacing the setup.py file in your local directory with the following:

```python
import setuptools

setuptools.setup(
    name="weakformghnn",
    version="1.0.0",
    author="Kevin L. Course, Trefor W. Evans, Prasanth B. Nair",
    author_email="kevin.course@mail.utoronto.ca",
    description="PyTorch implementation of weak form generalized Hamiltonian learning.",
    url="https://github.com/coursekevin/weakformghnn",
    packages=setuptools.find_packages(),
    install_requires=['torch'],
    classifiers=[
        "Programming Language :: Python :: 3",
        "Operating System :: OS Independent",
    ],
)
```

And then installing via `pip install -e .` Let me know if this helps.

**Comment by IPuiggros** [comment]
The change in the setup.py file worked! Thank you very much for the help.

**Comment by coursekevin** [comment]
Great, thank you for your interest in our work!
